name: Validate React Native Workflow
on:
    push:
        branches:
            - main
            - master
            - init
            - release-*
    pull_request:
        branches:
            - main
            - master
            - init
            - release-*
        types: [opened, synchronize, reopened, edited]
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                platform: [android, ios]

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/cache@v2
              id: cache-packages
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              if: steps.cache-packages.outputs.cache-hit != 'true'
              run: yarn

            - name: Build Bundle
              run: npx react-native bundle --platform ${{ matrix.platform }} --dev false --entry-file index.js  --bundle-output ./${{ matrix.platform == 'android' && 'index.android.bundle' || 'index.ios.bundle' }}

            - uses: actions/github-script@v4.1.0
              env:
                  PLATFORM: ${{ matrix.platform }}
                  ENTRY_FILE: index.js
                  BUNDLE_FILE: ${{ matrix.platform == 'android' && 'index.android.bundle' || 'index.ios.bundle' }}
              with:
                  script: |
                      const script = require('./.github/actionHelpers/bundleSizeDiffHandler.js')
                      await script({github, context, core})
