name: Auto-create PR to main_2

on:
  pull_request:
    types: [closed]
    branches: [main_1]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main_2 branch
      uses: actions/checkout@v2
      with:
        ref: main_2

    - name: Fetch changes from the merged PR
      run: git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-merge

    - name: Cherry-pick changes from merged PR
      run: git cherry-pick pr-merge

    - name: Create pull request to main_2
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'Automatically created PR from main_1 to main_2'
        commit-message: 'Cherry-picked changes from main_1 PR'
        head: 'pr-merge'
        base: 'main_2'