name: create-pr-from-main-2

on:
  pull_request:
    types: [closed]
    branches: [main_1]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         ref: main_2

      - name: Get PR details
        id: get_pr
        uses: peter-evans/get-pull-request@v3
        with:
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Create new branch
        run: git checkout -b ${{ steps.get_pr.outputs.data.head.ref }}-0.66.3

      - name: Cherry-pick PR changes
        run: git cherry-pick -n ${GITHUB_SHA} && git reset

      - name: Create PR to main_2
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ steps.get_pr.outputs.data.title }}
          body: ${{ steps.get_pr.outputs.data.body }}
          head: ${{ steps.get_pr.outputs.data.head.ref }}-0.66.3
          base: main_2
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}