name: Create PR from main_2

on:
  pull_request:
    types: [closed]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main_1'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main_2
    - name: Create new branch
      id: new_branch
      run: |
        git fetch --all
        git checkout -b ${{ github.event.pull_request.head.ref }}-0.66.3
    - name: Get pull request changes
      id: pr_changes
      run: |
        git diff --binary HEAD~1..HEAD > pr_changes.diff
    - name: Apply changes to new branch
      run: |
        git apply pr_changes.diff
        git add .
        git commit -m "cherry-pick from PR ${{ github.event.pull_request.number }} by ${{ github.event.pull_request.user.login }}"
    - name: Push changes to new branch
      run: |
        git push origin ${{ steps.new_branch.outputs.new_branch_name }}
    - name: Create new PR
      uses: peter-evans/create-pull-request@v3
      with:
        title: ${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.body }}
        commit-message: ${{ github.event.pull_request.title }}
        branch: ${{ steps.new_branch.outputs.new_branch_name }}
        base: main_2
        labels: ${{ join(github.event.pull_request.labels.*.name, ',') }}