name: Auto-create PR to main_2

on:
  pull_request:
    types: [closed]
    branches: [main_1]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main_2 branch
      uses: actions/checkout@v2
      with:
        ref: main_2

    - name: fetch
      run: git fetch --all

    - name: Cherry-pick changes of merged PR that triggered the event
      run: git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}

    - name: Create pull request to main_2
      uses: peter-evans/create-pull-request@v3
      with:
        title:  ${{ github.event.pull_request.title }}
        commit-message: 'Cherry-picked changes from main_1 PR'
        body: ${{ github.event.pull_request.body }}
        labels: ${{ join(github.event.pull_request.labels.*.name, ',') }}
        head: 'pr-merge'
        base: 'main_2'