name: Create Draft Adhoc release

on:
  workflow_dispatch:
    inputs:
      platformType:
        description: 'Android or Ios'
        default: 'android'
        type: choice
        options:
          - android
          - ios

env:
  branch: ${{ github.ref }}
  platform: ${{ github.event.inputs.platformType }}

jobs:
  createRelease:
    name: 'Create Tag and Adhoc Draft release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ env.branch }}

      - name: Read React Native Version
        run: |
          echo "rn_version=$(grep -oP '(?<="react-native": ")[^"]+' package.json)" >> $GITHUB_ENV
      
      - name: Set Tag IN ENV 
        run: |
          echo "tag_name=v_${{ env.platform }}_${{ env.rn_version }}" >> $GITHUB_ENV
      
      - name: Create Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ env.tag_name }} -m "version v_${{ env.platform }}_${{ env.rn_version }}"
          git push --tags
      
      - name: Create release
        uses: ncipollo/release-action@v1.10.0
        id: 'create-release'
        with:
            tag: ${{ env.tag_name }}
            generateReleaseNotes: true
            draft: true