name: Test Coverage Difference

on: pull_request

jobs:
  jest:
    runs-on: ubuntu-latest
    
    steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.X
                  registry-url: 'https://registry.npmjs.org'

            - name: Install
              run: yarn install --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - run: npm build

            - name: TestCoverage
              id: testCovergae
              uses: anuraag016/Jest-Coverage-Diff@master
              with:
                  accessToken: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
                  fullCoverageDiff: false
                  runCommand: "npx jest --passWithNoTests --collectCoverageFrom='[\"src/**/*.{js,jsx,ts,tsx}\"]' --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit --detectOpenHandles test/.*test.*"
