name: Push Release Slack Notificaion
on:
  push:
    branches:
      - main
      - master
env:
  platform: 'android'

jobs:

  codePush:
    runs-on: ubuntu-latest
    name: "Code Push"
    steps:
      - name: Get RN versiom
        env:
         TAG: ${{ 'ueu_bhdhc_0.71.7' }}
        run: echo "rn-version=${TAG##*_}" >> $GITHUB_ENV

      - name: print rn-version in the environment
        run: |
          echo "rn-version1: ${{ env.rn-version }}"

  versionUpgrade_0_71_7:
    name: Bump Version main
    runs-on: ubuntu-latest
    needs: codePush
    steps:
      - name: print rn-version in the environment
        run: |
          echo "rn-version2: ${{ env.rn-version }}"
