name: Example Workflow

on:
  push:
    branches:
      - main
      - master

env:
  rn_version: "1.2.3_beta_gamma_456_op_0.71.7"
  yu-version: ${{ '1.2.3_beta_gamma_456_op_0.71.7' }}##*_

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Last Element of String
        env:
         TAG: ${{ env.rn_version }}
        run: |
          # Set the rn-version in the environment variable
          echo "rn-version=${TAG##*_}" >> $GITHUB_ENV

      - name: Print rn-version from env
        run: |
          # Print the rn-version from the environment variable
          echo "rn-version: ${{ env.rn-version }}"
          echo "yu-version: ${{ env.yu-version }}"