name: Push Release Slack Notificaion
on:
  push:
    branches:
      - main
      - master
env:
  platform: "android"

jobs:
  getRnVersion:
    runs-on: ubuntu-latest
    outputs:
      rn-version: ${{ steps.step1.outputs.rn-version }}
    env:
      TAG: ${{ 'ueu_bhdhc_0.71.7' }}
    steps:
      #split TAG by '_' and get last element which is the RN version
      - id: step1
        run: echo "rn-version=${TAG##*_}" >> "$GITHUB_OUTPUT"

  codePush:
    runs-on: ubuntu-latest
    needs: getRnVersion
    name: "Code Push"
    steps:
      - name: Set the rn-version in the environment variable
        run: |
          echo "rn-version=${{ needs.getRnVersion.outputs.rn-version }}" >> $GITHUB_ENV

      - name: print rn-version in the environment
        run: |
          echo "rn-version1: ${{ env.rn-version }}"

  versionUpgrade_0_71_7:
    name: Bump Version main
    if: ${{ needs.getRnVersion.outputs.rn-version == '0.71.7' && env.platform == 'android'}}
    runs-on: ubuntu-latest
    needs: [getRnVersion, codePush]
    steps:
      - name: Set the rn-version in the environment variable
        run: |
          echo "rn-version=${{ needs.getRnVersion.outputs.rn-version }}" >> $GITHUB_ENV

      - name: print rn-version in the environment
        run: |
          echo "rn-version2: ${{ env.rn-version }}"

      - name: checkout to main
        run: |
          echo "namE is ${{ env.rn-version == '0.71.7' && 'main' || 'main-${{ env.rn-version }}' }}"
