name: Example Workflow

on:
  push:
    branches:
      - main

env:
  rn_version: "1.2.3_beta_gamma_456_op_0.71.7"

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Last Element of String
        run: |
          # Use parameter expansion to get the last field
          last_field="${{ env.rn_version##*_ }}"

          # Print the last field
          echo "Last field: $last_field"

          # Set the rn-version in the environment variable
          echo "rn-version=$last_field" >> $GITHUB_ENV

      - name: Print rn-version from env
        run: |
          # Print the rn-version from the environment variable
          echo "rn-version: ${{ env.rn-version }}"