name: Push Release Slack Notificaion
on:
  push:
    branches:
      - main
      - master
env:
  platform: "android"

jobs:
  getRnVersion:
    runs-on: ubuntu-latest
    outputs:
      rn-version: ${{ steps.step1.outputs.rn-version }}
    env:
      TAG: ${{ 'ueu_bhdhc_0.71.7' }}
    steps:
      #split TAG by '_' and get last element which is the RN version
      - id: step1
        run: echo "rn-version=${TAG##*_}" >> "$GITHUB_OUTPUT"

  codePush:
    runs-on: ubuntu-latest
    needs: getRnVersion
    name: "Code Push"
    env:
     rn-version: ${{ needs.getRnVersion.outputs.rn-version }}
    steps:
      - name: print rn-version in the environment
        run: |
          echo "rn-version1: ${{ rn-version }}"

  versionUpgrade_0_71_7:
    name: Bump Version main
    runs-on: ubuntu-latest
    needs: [getRnVersion, codePush]
    env:
     rn-version: ${{ needs.getRnVersion.outputs.rn-version }}
    steps:
      - name: print rn-version in the environment
        run: |
          echo "rn-version2: ${{ rn-version }}"

      - name: checkout to main
        run: |
          echo "nam is ${{ rn-version == '0.71.7' && format('main-{0}',rn-version) || 'main' }}"
