name: Example Workflow

on:
  push:
    branches:
      - main
      - master

env:
  rn_version: "1.2.3_beta_gamma_456_op_0.71.7"

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Last Element of String
        env:
         tag-name: ${{ env.rn_version }}
        run: |
          # Use parameter expansion to get the last field
          rn-version="${tag-name##*_}"

          # Print the last field
          echo "RN Version: $rn-version"

          # Set the rn-version in the environment variable
          echo "rn-version=$rn-version" >> $GITHUB_ENV

      - name: Print rn-version from env
        run: |
          # Print the rn-version from the environment variable
          echo "rn-version: ${{ env.rn-version }}"